[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "miniflux_mail_digest"
authors = [{name = "Maor Kadosh", email = "git@avocadosh.xyz"}]
dependencies = ["miniflux==0.0.15", "beautifulsoup4==4.12.0", "python-dotenv==1.0.0"]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]

[tool.black]
line-length = 100

[project.scripts]
miniflux-mail-digest = "miniflux_mail_digest:main"
